name: Notify Pushes on Telegram
on: [push]
jobs:

  build:
    name: Send Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Notify to @DevChangeLogs_byMPTeam
      uses: appleboy/telegram-action@master
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      with:
        args: An new commit, ${{ commit.sha }} has been pushed to ${{ repo }} GitHub repository.
